# Generated by Django 4.2.8 on 2025-04-07 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa_hoc', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaiLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tai_lieu', models.CharField(max_length=50, unique=True)),
                ('ten_tai_lieu', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('file_tai_lieu', models.FileField(upload_to='tai_lieu/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('XLS', 'XLS'), ('XLSX', 'XLSX'), ('PPT', 'PPT'), ('PPTX', 'PPTX'), ('ZIP', 'ZIP'), ('RAR', 'RAR'), ('OTHER', 'Khác')], default='PDF', max_length=10)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tai_lieu', to='DocumentManagement.khoahoc')),
            ],
        ),
    ]
