# Generated by Django 5.2 on 2025-04-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialsFree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
