# Generated by Django 4.2.8 on 2025-04-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa_hoc', models.CharField(choices=[('English - Level 1', 'English - Level 1'), ('English - Level 2', 'English - Level 2'), ('English - Level 3', 'English - Level 3')], default='English - Level 1', max_length=100)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
            },
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=50)),
                ('so_luong_hoc_vien', models.IntegerField(default=0)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('trang_thai', models.CharField(choices=[('Đang học', 'Đang học'), ('Đã kết thúc', 'Đã kết thúc'), ('Chưa bắt đầu', 'Chưa bắt đầu')], default='Đang học', max_length=20)),
                ('khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lop_hoc', to='ManageClass.khoahoc')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
            },
        ),
    ]
