# Generated by Django 5.2 on 2025-04-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageClass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lophoc',
            name='khoa_hoc',
        ),
        migrations.DeleteModel(
            name='KhoaHoc',
        ),
        migrations.DeleteModel(
            name='LopHoc',
        ),
    ]
